### ISSUE TITLE
Update status of the repository

### ISSUE THREAD

**Issue by aereal** [motemen/prchecklist#53]
GitHub's repository status feature is very useful.

refs. https://developer.github.com/v3/repos/statuses/

- (Set `checklist_complete` status as pending if checklist created)
- Set `checklist_complete` status as success if completed

**Comment by motemen** [comment]
![image](https://user-images.githubusercontent.com/8465/41011441-e55d234c-6977-11e8-99e9-73bb61c35f8f.png)

Have just tried on https://github.com/motemen/test-repository/pull/2 / https://prchecklist.herokuapp.com/motemen/test-repository/pull/2/qa . Working properly.

Would be nice to have ...

- Stage information (eg. qa / staging / production)
- "Detail" link

😉

**Comment by motemen** [comment]
![image](https://user-images.githubusercontent.com/8465/41035449-aef41464-69c7-11e8-984f-b2d2ef2003d8.png)

Thanks! Finally released v2.2.2 .
